# Generated by Django 5.0.6 on 2024-07-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="student_details_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("1", "ADMIN"), ("2", "TEACHER"), ("3", "STUDENT")],
                max_length=50,
            ),
        ),
    ]
