# Generated by Django 5.0.6 on 2024-07-08 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_staff"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
