# Generated by Django 5.0.6 on 2024-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_staff_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("1", "ADMIN"), ("2", "STAFF"), ("3", "STUDENT")],
                max_length=50,
            ),
        ),
    ]
