# Generated by Django 5.0.6 on 2024-07-08 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_timetable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Timetable",
        ),
    ]
