# Generated by Django 5.0.6 on 2024-07-10 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_timetable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Timetable",
        ),
    ]
