# Generated by Django 5.0.6 on 2024-07-14 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_alter_student_student_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deletedstudentbackup",
            old_name="course",
            new_name="course_id",
        ),
        migrations.RenameField(
            model_name="deletedstudentbackup",
            old_name="deletion_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="deletedstudentbackup",
            name="password",
        ),
        migrations.RemoveField(
            model_name="deletedstudentbackup",
            name="student_details_link",
        ),
        migrations.RemoveField(
            model_name="deletedstudentbackup",
            name="username",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deletedstudentbackup",
            name="deleted_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deletedstudentbackup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("1", "ADMIN"), ("2", "STAFF"), ("3", "STUDENT")],
                default="1",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="deletedstudentbackup",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="deletedstudentbackup",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="deletedstudentbackup",
            name="student_id",
            field=models.IntegerField(),
        ),
    ]
