# Generated by Django 5.0.6 on 2024-07-15 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_rename_course_deletedstudentbackup_course_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="is_deleted",
        ),
        migrations.DeleteModel(
            name="DeletedStudentBackup",
        ),
    ]
