# Generated by Django 5.0.6 on 2024-07-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_remove_staff_is_deleted_delete_deletedstudentbackup"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
