# Generated by Django 5.0.6 on 2024-07-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_staff_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="staff_id",
            field=models.CharField(default="default_id", max_length=20),
        ),
    ]
